[package]
name = "http-server"
version = "0.3.0"
authors = ["Damjan Georgievski <gdamjan@gmail.com>"]
license = "MIT"
readme = "README.md"

[dependencies]
actix-web = { git = "https://github.com/actix/actix-web.git" }
bytes = "0.4"
futures = "0.1"
tar = "0.4"
percent-encoding = "1.0"
htmlescape = "0.3"

[profile.release]
#opt-level = 's'
lto = true
panic = 'abort'
