[package]
name = "http-server"
version = "0.9.0"
authors = ["Damjan Georgievski <gdamjan@gmail.com>"]
license = "MIT"
readme = "README.md"
homepage = "https://github.com/gdamjan/http-server-rs"
edition = "2018"

[dependencies]
actix-web = "0.7"
bytes = "0.4"
clap = "2"
env_logger = "*"
log = "*"
futures = "0.1"
tar = "0.4"
percent-encoding = "1.0"
htmlescape = "0.3"

[profile.release]
opt-level = 'z'
lto = true
panic = 'abort'
