[package]
name = "http-server"
version = "0.4.0"
authors = ["Damjan Georgievski <gdamjan@gmail.com>"]
license = "MIT"
readme = "README.md"

[dependencies]
actix-web = "0.7"
bytes = "0.4"
clap = "2"
env_logger = "*"
futures = "0.1"
tar = "0.4"
percent-encoding = "1.0"
htmlescape = "0.3"

[profile.release]
#opt-level = 's'
lto = true
panic = 'abort'
