name: Make a release

on:
  repository_dispatch:
    types: [tag-created]

jobs:
  release:
    name: Build and Release
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            artifact_name: http-server
            asset_name: http-server-$tag-linux-amd64.zip
          - os: macos-latest
            artifact_name: http-server
            asset_name: http-server-$tag-macos-amd64.zip
          - os: windows-latest
            artifact_name: http-server.exe
            asset_name: http-server-$tag-windows.zip
    steps:
      - uses: actions/checkout@v2

      - name: Build project
        run: cargo build --release --locked

      - name: Pre-release
        run: |
              strip target/release/${{ matrix.artifact_name }}
              zip ${{ matrix.asset_name }} -j target/release/${{ matrix.artifact_name }}

      - name: Upload binary to release
        uses: svenstaro/upload-release-action@v1-release
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{ matrix.asset_name }}
          tag: ${{ github.event.client_payload.new_version }}
