name: Make a release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write
  id-token: write

jobs:
  release:
    name: Build and Release
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target_file: http-server
            artifact: http-server-${{ github.ref_name }}-linux-amd64
          - os: macos-latest
            target_file: http-server
            artifact: http-server-${{ github.ref_name }}-macos-amd64
          - os: windows-latest
            target_file: http-server.exe
            artifact: http-server-${{ github.ref_name }}-windows.exe
    steps:
      - uses: actions/checkout@v4
      - uses: sigstore/cosign-installer@v3.4.0

      - name: Build project
        run: cargo build --release --locked

      - name: Prepare artifact
        run: cp target/release/${{ matrix.target_file }} ${{ matrix.artifact }}

      - name: Sign artifact
        run: |
          cosign sign-blob --yes \
            --output-signature ${{ matrix.artifact }}.sig \
            --output-certificate ${{ matrix.artifact }}.cert \
            ${{ matrix.artifact }}

      - name: Upload artifacts to github-releases
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: http-server-*
          file_glob: true
          tag: ${{ github.ref }}
