name: Make a release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write
  id-token: write

jobs:
  release:
    name: Build and Release
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            artifact_name: http-server
            asset_name: http-server-$tag-linux-amd64.zip
            zipcmd: zip -j
          - os: macos-latest
            artifact_name: http-server
            asset_name: http-server-$tag-macos-amd64.zip
            zipcmd: zip -j
          - os: windows-latest
            artifact_name: http-server.exe
            asset_name: http-server-$tag-windows.zip
            zipcmd: 7z a -tzip
    steps:
      - uses: actions/checkout@v4
      - uses: sigstore/cosign-installer@v3.4.0

      - name: Build project
        run: cargo build --release --locked

      - name: make release.zip
        run: ${{ matrix.zipcmd}} ${{ matrix.asset_name }} target/release/${{ matrix.artifact_name }}

      - name: Sign release.zip
        run: cosign sign-blob --yes --output-signature ${{ matrix.asset_name }}.sig --output-certificate ${{ matrix.asset_name }}.cert ${{ matrix.asset_name }}

      - name: Upload artifacts to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: http-server-*
          file_glob: true
          tag: ${{ github.ref }}
